
name: Benjamin Campagna
description: BenJamin since 1998

avatar: https://raw.githubusercontent.com/bencampa/ben_site/master/images/made_logo.png

# Your favicon (appears on the browser tab) image URL, it is recommended to use a smaller (64px × 64px) image
favicon: https://raw.githubusercontent.com/bencampa/ben_site/master/images/favicon.png
navigation:
  - name: Work Experience
    url: /
  - name: Projects
    url: /projects
  - name: About
    url: /about
  - name: Contact me
    url: /contact

# articles per page
paginate: 5

# Distinct markup for article introduction
excerpt_separator: <!-- more -->

# Your social network links, they will appear as icons in the footer of your website, optional
footer-links: 
  email: bencampa@umich.edu 
  github: https://github.com/bencampa
  instagram: https://www.instagram.com/ben_campagna/
  linkedin: https://www.linkedin.com/in/ben-campagna-22736114a/

footer-text: Copyright (c) 2019 (Not actually copyrighted just wanted to look official)

disqus: BenC #shortname

gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

#Google Analytics web tracking code
google_analytics:

# Enter your website domain name (if you do not add your own domain name, but use the domain name assigned directly by GitHub pages, you can omit it
url: https://bencampagna.com

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /site


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

