
name: Benjamin Campagna
description: BenJamin since 1998

avatar: https://raw.githubusercontent.com/bencampa/ben_site/master/images/made_logo.png

favicon: https://raw.githubusercontent.com/bencampa/ben_site/master/images/favicon.png
navigation:
  - name: Work Experience
    url: /
  - name: Projects
    url: /projects
  - name: About
    url: /about
  - name: Contact me
    url: /contact

# articles per page
paginate: 5


excerpt_separator: <!-- more -->

footer-links: 
  email: bencampa@umich.edu 
  github: https://github.com/bencampa
  instagram: https://www.instagram.com/ben_campagna/
  linkedin: https://www.linkedin.com/in/ben-campagna-22736114a/

footer-text: Copyright (c) 2019 (Not actually copyrighted just wanted to look official).


# Enter your website domain name (if you do not add your own domain name, but use the domain name assigned directly by GitHub pages, you can omit it
domain: bencampagna.com


baseurl: /ben_site


#
# !! DONT CHANGE !!
#

permalink: /:title/
paginate_path: /page:num/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 
plugins:
  - jekyll-sitemap 
  - jekyll-feed 
  - jekyll-paginate


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

